main: dev.thorinwasher.blockanimator.papertest.TestPlugin
name: TestPlugin
version: ${version?:unknown}
api-version: 1.17
depend:
  - WorldEdit
commands:
  animate:
    description: "Test command for animating blocks"