name: Publish package to GitHub Packages
on:
  push:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: calculate version
        id: calculate-version
        uses: bitshifted/git-auto-semver@v1.1.0
        with:
          main_branch: main
          create_tag: true
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2

      - name: Publish block animation API
        run: bash gradlew :api:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.calculate-version.outputs.version-string }}

      - name: Publish paper block animation API
        run: bash gradlew :paper:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.calculate-version.outputs.version-string }}

      - name: Publish minestom block animation API
        run: bash gradlew :minestom:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.calculate-version.outputs.version-string }}