name: Publish package to maven central
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Parse version
        run: |
          TAG=${{ github.event.release.tag_name }}
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2

      - name: Check if project compiles
        run: bash gradlew compileJava

      - name: Publish block animation API
        run: bash gradlew :api:publishAndReleaseToMavenCentral --no-configuration-cache
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.USER_TOKEN_MAVEN_CENTRAL }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.USER_KEY_MAVEN_CENTRAL }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}

      - name: Publish paper block animation API
        run: bash gradlew :paper:publishAndReleaseToMavenCentral --no-configuration-cache
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.USER_TOKEN_MAVEN_CENTRAL }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.USER_KEY_MAVEN_CENTRAL }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}

      - name: Publish minestom block animation API
        run: bash gradlew :minestom:publishAndReleaseToMavenCentral --no-configuration-cache
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.USER_TOKEN_MAVEN_CENTRAL }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.USER_KEY_MAVEN_CENTRAL }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}

      - name: Publish world edit schematic loading interface
        run: bash gradlew :worldedit:publishAndReleaseToMavenCentral --no-configuration-cache
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.USER_TOKEN_MAVEN_CENTRAL }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.USER_KEY_MAVEN_CENTRAL }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}