name: Publish package to maven central
on:
  push:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Calculate version
        uses: paulhatch/semantic-version@v5.4.0
        id: calculate-version
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}"
          # If enabled, diagnostic information will be added to the action output.
          debug: true
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2

      - name: Check if project compiles
        run: bash gradlew compileJava

      - name: Publish block animation API
        run: bash gradlew :api:publishAndReleaseToMavenCentral --no-configuration-cache
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.calculate-version.outputs.version }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.USER_TOKEN_MAVEN_CENTRAL }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.USER_KEY_MAVEN_CENTRAL }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}

      - name: Publish paper block animation API
        run: bash gradlew :paper:publishAndReleaseToMavenCentral --no-configuration-cache
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.calculate-version.outputs.version }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.USER_TOKEN_MAVEN_CENTRAL }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.USER_KEY_MAVEN_CENTRAL }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}

      - name: Publish minestom block animation API
        run: bash gradlew :minestom:publishAndReleaseToMavenCentral --no-configuration-cache
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.calculate-version.outputs.version }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.USER_TOKEN_MAVEN_CENTRAL }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.USER_KEY_MAVEN_CENTRAL }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}
          
      - name: Create release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: v${{ steps.calculate-version.outputs.version }}